language: node_js
sudo: false
node_js:
- 6.5 # Latest
- 4.5 # LTS
- 0.10 # Earliest version supported
cache:
  directories:
  - $HOME/.npm
before_install: npm -g install npm@latest
script: npm test -- --timeout 15000
after_success:
- cat coverage/lcov/lcov.info | ./node_modules/.bin/codecov
